services: 
  # mongodb:
  #   image: mongo:latest
  #   ports: 
  #     - "27017:27017"
  #   volumes: 
  #     - mongodb-data:/data/db



  backend:
    build: 
      context: ./
      target: development
    ports:
      - "5000:5000" 

volumes:
  mongodb-data: